# Generated by Django 6.0.4 on 2026-05-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="price",
        ),
    ]
